### ISSUE TITLE
Add Ethereum Classic indexation

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-search#24]

**Comment by litvintech** [comment]
@hleb-albau Please, provide description of task in the meaning of changing indexation proccess to kafka-connector

**Comment by hleb-albau** [comment]
Create jvm based app that:

- connects to classic network, obtains blocks
- split blocks to search entities
- save that entities as batch statement in cassandra
- save processing state to cassandra

**Comment by litvintech** [comment]
@YodaMike please connect your branch to this issue and wrote checklist-roadmap with @hleb-albau

**Comment by hleb-albau** [comment]
Done in chain_pump

**Comment by mrh2022** [comment]
hello guys how can i recove my etc from metamask?

**Comment by mrh2022** [comment]
im going crazy pls answer
