### ISSUE TITLE
Add two-phase kafka-cassandra commit for non-idempotents queries

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#26]
Address service has main purpose of atomic updating addresses values in cassandra. To archive this, we split some entity (for example bitcoin transaction) into N address updates, transactionally(see kafka exactly-once) save this entities into kafka. Than read topics with updates, and apply them on cassandra one-by-one. 
There is case, when we already update address values in cassandra, but application cant successfully save consumer offset and exits . Also, keep in mind possibility of parallel address updates.

**Comment by litvintech** [comment]
@YodaMike Please check description/state of this task and comment to

**Comment by YodaMike** [comment]
Description and state are reliable

**Comment by hleb-albau** [comment]
Not actual.
