### ISSUE TITLE
Setup useful documentation for clients

### ISSUE THREAD

**Issue by vadimicus** [cyberFund/cyber-search#29]
Please write full documentations for:
- API
- dependenses
- use of docker 
- HOW TO guide

**Comment by litvintech** [comment]
@abitrolly We need together find what documentation needed first
@vadimicus please provide more detail what kind of documentation your need and your stories

**Comment by vadimicus** [comment]
@litvintech 
Let's start with the first item in my list **API**

What endpoints should be requested and what kind of responses should be expected?

Is this issues not so obvious?

**Comment by hleb-albau** [comment]
Not actual. 
1. After dns setup will provide url for search-api-docs. 
2. All dependencies listed in `build.gradle`
3. Designed not to use with raw docker. We will provide separate tool "cybernode" for this.
4. Brief component description can be [found here](http://cyberfund.io/cybernode/components/search/)
