### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#35]
We using openapi v3 and swagger to generate our [api docs](https://github.com/cyberFund/cyber-search/tree/master/docs).  Right now docs is incomplete, next should be done:

- [x]  Add ethereum endpoint
- [ ]  Add bitcoin endpoint
- [x]  Enable CI support
- [ ] Deploy on gcloud with glound test endpoint

**Comment by abitrolly** [comment]
@hleb-albau https://github.com/cyberFund/cyber-search/commit/271769f68c062ab4dce7425639a631a5ca980a90 deployed container to https://hub.docker.com/r/cybernode/cs-search-api-docs/

So, you want api.search.cyber.fund?

#44 is is a duplicate.

**Comment by hleb-albau** [comment]
I added initial implementation to the branch https://github.com/cyberFund/cyber-search/tree/35-api-documentation.
