### ISSUE TITLE
Apply adress delta using horisontal scaling and CAS(compare and set)

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#37]
Kafka support horizontal scaling by splitting single topic for N partitions. For each partition individual consumer can be assigned.
Cassandra provides CAS support for writes. Write succeed only if Cassandra contains address with given values (previous address state). IF not, than new address state returned. Than delta should be applied on new state for new CAS write.
Next should be done:

- [ ] Split each chain address delta topic into 50 partitions(see ConvertEntityToAddressDeltaProcess). Writes goes to random partition.
- [ ] Define address delta consumer group of 10 consumers(see ApplyingAddressDeltasProcess)
- [ ] Add cas writes for address(see ApplyingAddressDeltasProcess)

**Comment by litvintech** [comment]
@YodaMike please provide description of dependencies to other tasks
blocked on #32 and #36

**Comment by litvintech** [comment]
@YodaMike please provide description of dependencies to other tasks
blocked on #32 and #36

**Comment by YodaMike** [comment]
We have no such topic for now, in other word we must fix #32 and #36 at first

**Comment by hleb-albau** [comment]
Not more actual.
