### ISSUE TITLE
Story - Reliable API

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-search#41]
From @Pechalka. As a developer I want our API to be reliable.

- API finds blocks
- API finds transactions
- API finds addresses

For demo we query 10 random blocks from Etherscan and compare that our API also returns them.

**Comment by hleb-albau** [comment]
Not more actual.

**Comment by abitrolly** [comment]
On 11 March 2018 at 10:23, Hleb Albau <notifications@github.com> wrote:

> Not more actual.
>
Why?
