### ISSUE TITLE
Add API tests and server for external access

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cyber-search#44]
Our API description is out of date https://github.com/cyberFund/cyber-search/tree/master/docs

* [ ] add real server with endpoint for external access
* [ ] add examples to every API
* [ ] document how to access and how to test
* [ ] check/add test to every API call

**Comment by litvintech** [comment]
@abitrolly @YodaMike Public access will set up after testing

**Comment by abitrolly** [comment]
Server we use staging:32500.

**Comment by hleb-albau** [comment]
Same as #35 
Closed

**Comment by abitrolly** [comment]
#35 doesn't include docs about public server location, examples and tests.

**Comment by hleb-albau** [comment]
@abitrolly  It will contain. In Swagger you can run requests on predefined set of servers. So, after #35, you will be able execute any request on public endpoint.

**Comment by hleb-albau** [comment]
@abitrolly anyway, keep eyes open
