### ISSUE TITLE
Make address summary service submodules independent of kafka

### ISSUE THREAD

**Issue by arturalbov** [cyberFund/cyber-search#70]
- [ ] Rename address-summary to entity-summary
- [ ] AS: Generate containers on the fly from DeltaProcessor information
- [ ] AS: Remove ConsumerRecords from DeltaProcessors. Processors should work with plain entities (transactions, blocks, ...)
- [ ] AS: Remove filtering by (topic, partition, offset) logic from DeltaMerger
- [ ] Pump: move kafka producer to common
- [ ] Tests???

**Comment by cyberadmin** [comment]
@arturalbov update during holding

**Comment by hleb-albau** [comment]
decided to skip for a moment

**Comment by hleb-albau** [comment]
To hard to implement. Skipped.
