### ISSUE TITLE
Base Alerting Implementation For Ethereum Pump

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#71]
- [ ]  Telegram Notification Chanel
- [ ]  Alerting of Stopped Indexation
- [ ]  Use Kafka exporter instead of self written metrics
- [ ] Redesign Ethereum Dashboards

**Comment by hleb-albau** [comment]
blocked by https://github.com/grafana/grafana/issues/11400

**Comment by hleb-albau** [comment]
Implemented next alerts:
- ethereum pump is alive
- ehtereum dump tx queue size < 1000
- ethereum contract summary calculation tx queue size < 1000
Notification channels:
-telegram chat  "-309935318"

**Comment by abitrolly** [comment]
If https://github.com/grafana/grafana/issues/11400 still actual? Good candidate for #74.

**Comment by hleb-albau** [comment]
@abitrolly Yes, actual. We found work around, for our case, but functionality is broken.
