### ISSUE TITLE
Bitcoin multisig transaction

### ISSUE THREAD

**Issue by hleb-albau** [cyberFund/cyber-search#8]
Bitcoin transaction output could contains multiple addresses. 
Define model for this

See https://blockchain.info/tx/56214420a7c4dcc4832944298d169a75e93acf9721f00656b2ee0e4d194f9970

**Comment by 21xhipster** [comment]
I suppose it is better to treat outputs as standalone objects like [Blockchair](https://blockchair.com/bitcoin/address/1NjWoz1djcNo2BhMLewLdepqUm2NBMqMxp) does.

**Comment by hleb-albau** [comment]
We can present it even more better. But here is a question about our internal model  of such transactions. Right now i just store addresses as comma separated list.
```
                 /    output 1
input 1 ---------
                 \    output 2
```
